Repository icssc/ZotMeet, pull requests merged in 2024-03, with the labels that each got.

#61 Migrate Drizzle
  package.json
  pnpm-lock.yaml
  src/lib/db/drizzle.ts
  src/lib/db/postgres.ts
  src/lib/db/schema.ts
Labels: enhancement, codefix

#67 Summary page functionality
  drizzle.config.ts
  migrations/0000_worried_nightcrawler.sql
  migrations/0001_vengeful_korg.sql
  migrations/meta/0000_snapshot.json
  migrations/meta/0001_snapshot.json
  migrations/meta/_journal.json
  package.json
  pnpm-lock.yaml
  src/lib/components/summary/ScheduledMeetings/AvailabilityIndicator.svelte
  src/lib/db/postgres.ts
  src/lib/db/schema.ts
  src/routes/api/availability/+server.ts
Labels: enhancement

#78 PR and Issue Templates
  .github/ISSUE_TEMPLATE/default-issue.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: codefix

#77 Remove future functionality from UI
  src/lib/components/navigation/shared/NavButton.svelte
  src/lib/components/navigation/shared/NavButtons.svelte
  src/lib/components/summary/ScheduledMeetings/ScheduledMeetingCard.svelte
  src/lib/components/summary/UnscheduledMeetings/UnscheduledMeetingsList.svelte
  src/routes/+layout.svelte
  src/routes/summary/+page.svelte
Labels: enhancement
